### ISSUE TITLE
Make 61850 more easy: show file relations

### ISSUE THREAD

**Issue by Laurentjg** [openscd/openscd.github.io#2]
I do experience that OpenSCD makes 61850 more easy by adding UX to the data. To even further improve this concept, it would be helpful to integrate descriptions and relations of the different files to the UX, e.g. as on this website: https://eitsgroup.net/pages/iec-61850-types-of-scl-files/  (file descriptions and diagram at the bottom).

**Comment by JakobVogelsang** [comment]
Hi @Laurentjg thank you for the comment. For future issues please go to official [OpenSCD repository](https://www.github.com/openscd/open-scd) as this is only the "publishing" space. 

To your question: OpenSCD will in future releases be able to participate in the engineering process with the roles defined in IEC 61850-6 and will then take different file extensions into account. I agree, this is very necessary so that it can become a `whatever...configurator`. At this moment, we are adding simple manipulation capabilities, aiming to reach our first goal to become a complete editor for SCL files. For this goal, t is not really necessary to make a distinction between those extensions, and it even adds an unnecessary complexity to it. Do you think we make a mistake doing it lake that?

**Comment by Laurentjg** [comment]
Hi @JakobVogelsang, I see it, I'm in the io-repository :-( 
I don't think it's a mistake of doing it later, however I only think it's a strong message to the broader community that the work you are doing will be the core of each ones engineering process. If this message is clear, then the contribution and the value of your work including compatibility to the engineering process will be highlighted. So just a thought.
